# Generated by Django 4.2.15 on 2024-09-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="customuser",
            name="interest",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="customuser",
            name="major",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="", max_length=60),
        ),
    ]
